import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modalOverlay: { flex: 1 },
  modalContent: { flex: 1 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', padding: 20 },
  headerText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  keyboardAvoidingView: { flex: 1 },
  scrollContent: { paddingBottom: 60 },
  heroImage: { width: '90%', height: 300, borderRadius: 30, alignSelf: 'center' },
  infoPadding: { padding: 25 },
  species: { color: '#8cc285', fontSize: 14, fontWeight: '700', textTransform: 'uppercase' },
  name: { color: '#fff', fontSize: 32, fontWeight: 'bold', marginBottom: 20 },
  actionRow: { flexDirection: 'row', gap: 12, marginBottom: 18 },
  actionButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryAction: { backgroundColor: '#315f34' },
  actionButtonText: { color: '#fff', fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
  primaryActionText: { color: '#fff', fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.7, textAlign: 'center' },
  sanctuaryCard: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    padding: 18,
    borderRadius: 24,
    marginBottom: 20,
  },
  sectionHeader: { color: '#fff', fontSize: 18, fontWeight: '600', marginBottom: 15 },
  ritualMetaRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  ritualMetric: { flex: 1 },
  cadenceControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 6,
  },
  cadenceButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cadenceButtonText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  careGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  careBox: { backgroundColor: 'rgba(255,255,255,0.1)', padding: 15, borderRadius: 20, width: '48%' },
  label: { color: 'rgba(255,255,255,0.5)', fontSize: 12 },
  value: { color: '#fff', fontSize: 14, fontWeight: '600', marginTop: 6 },
  editInput: {
    color: '#fff',
    borderBottomWidth: 1,
    borderColor: '#8cc285',
    marginTop: 5,
    paddingVertical: 5,
  },
  secretBox: {
    backgroundColor: '#111',
    padding: 20,
    borderRadius: 25,
    borderLeftWidth: 4,
    borderLeftColor: '#4f9a44',
    marginBottom: 20,
  },
  secretTitle: { color: '#fff', fontSize: 16, fontWeight: 'bold', marginBottom: 8 },
  secretText: { color: 'rgba(255,255,255,0.7)', lineHeight: 22 },
  editArea: {
    color: '#fff',
    fontSize: 14,
    lineHeight: 22,
    minHeight: 72,
    textAlignVertical: 'top',
  },
  timelineCard: {
    backgroundColor: 'rgba(255,255,255,0.07)',
    padding: 18,
    borderRadius: 24,
  },
  timelineEmpty: { color: 'rgba(255,255,255,0.55)', lineHeight: 20 },
  timelineItem: {
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
  },
  timelineType: {
    color: '#8cc285',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  timelineDetail: { color: '#fff', fontSize: 14, marginTop: 4, lineHeight: 20 },
  timelineDate: { color: 'rgba(255,255,255,0.58)', fontSize: 12, marginTop: 6 },
});
