import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 0.5,
  },
  backBtn: { padding: 4 },
  backArrow: { fontSize: 22, fontWeight: '300' },
  headerTitle: { fontSize: 17, fontWeight: '600' },
  editBtn: { fontSize: 16, fontWeight: '500' },
  scroll: { paddingHorizontal: 20, paddingBottom: 60 },
  avatarSection: { alignItems: 'center', paddingVertical: 32 },
  avatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  avatarInitials: { color: '#fff', fontSize: 30, fontWeight: '600' },
  username: { fontSize: 18, fontWeight: '600', marginBottom: 4 },
  tagline: { fontSize: 14 },
  statsRow: { flexDirection: 'row', gap: 12, marginBottom: 24 },
  statCard: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 16,
    borderRadius: 14,
    borderWidth: 0.5,
  },
  statVal: { fontSize: 20, fontWeight: '700' },
  statLabel: { fontSize: 12, marginTop: 2 },
  section: {
    borderRadius: 14,
    borderWidth: 0.5,
    marginBottom: 16,
    paddingHorizontal: 16,
    overflow: 'hidden',
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.8,
    paddingTop: 12,
    paddingBottom: 6,
  },
  field: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 13,
    borderBottomWidth: 0.5,
  },
  fieldLabel: { fontSize: 15, flex: 1 },
  fieldValue: { fontSize: 15, flex: 1.5, textAlign: 'right' },
  fieldInput: {
    fontSize: 15,
    flex: 1.5,
    textAlign: 'right',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  deleteText: { fontSize: 15, color: '#e53935', paddingVertical: 2 },
});
